### ISSUE TITLE
Git master fails to build on Ubuntu 18.10

### ISSUE THREAD

**Issue by prokoudine** [LuminanceHDR/LuminanceHDR#138]
```
[ 89%] Linking CXX executable luminance-hdr
/usr/bin/ld: //usr/lib/x86_64-linux-gnu/libQt5Positioning.so.5: bfd_elf_get_bfd_needed_list failed: Input/output error
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/luminance-hdr.dir/build.make:292: luminance-hdr] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/luminance-hdr.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

I can't seem to make heads or tails of it :) Maybe it's not even you and rather Ubuntu at fault. What info do you need?

**Comment by fcomida** [comment]
@prokoudine Hello, please test last change, it should have fixed your issue.

**Comment by prokoudine** [comment]
I'm afraid I get stuck in a different place now:

```
[ 80%] Building CXX object src/Viewers/CMakeFiles/viewers.dir/IGraphicsPixmapItem.cpp.o
In file included from /PATH/src/Viewers/IGraphicsPixmapItem.cpp:30:
/PATH/src/Viewers/ISelectionBox.h:31:10: error: /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QGraphicsRectItem: Input/output error
 #include <QGraphicsRectItem>
          ^~~~~~~~~~~~~~~~~~~
make[2]: *** [src/Viewers/CMakeFiles/viewers.dir/build.make:143: src/Viewers/CMakeFiles/viewers.dir/IGraphicsPixmapItem.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2204: src/Viewers/CMakeFiles/viewers.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by fcomida** [comment]
@prokoudine This time is not a linker issue. It's a I/O error reading an included file. Do you have access to another machine? I'd check the hard disk a/o the cables. It seems a hardware issue to me. I might be wrong.

**Comment by fcomida** [comment]
@prokoudine Any progress?

**Comment by prokoudine** [comment]
I sent the laptop to the service due to, apparently, failed SSD. Building on a workstation with Debian Unstable passes. Thanks!
