### ISSUE TITLE
Fails to build on Ubuntu 15.10: QPrinter: No such file or directory

### ISSUE THREAD

**Issue by ckorn** [LuminanceHDR/LuminanceHDR#11]
In the new Ubuntu version 15.10 there is a build error:
src/HelpBrowser/helpbrowser.cpp:48:20: fatal error: QPrinter: No such file or directory

This file should be included in the qtbase5-dev package:
http://packages.ubuntu.com/wily/i386/qtbase5-dev/filelist

This is the build log:
http://zulu309.server4you.de/build/logs/luminance_2.4.0-1~getdeb4~wily-i386-20151021-2332

The package is installed but it fails anyway.

**Comment by fcomida** [comment]
I have this in main CMakeLists.txt:

find_package(Qt5PrintSupport REQUIRED)

and in src/HelpBrowser/CMakeLists.txt:

qt5_use_modules(helpbrowser Core Concurrent Gui Widgets Xml WebKit
WebKitWidgets PrintSupport)

**Comment by ckorn** [comment]
Thanks.

Is 2.4.0 still the latest version? There has been no new tag for a long time.

**Comment by fcomida** [comment]
Yes it is. I have a patch fixing a small bug in TonemappingPanel I'm
sending to you. Another big issue is in HdrWizard, as soon as I make a
patch for it I'll send it to you as well.

Regards

**Comment by davideanastasia** [comment]
Are these changes in the CMake config upstream as well?

**Comment by fcomida** [comment]
No Davide, I haven't commited anything yet.
I wanna fix Exif now, I proposed the releasing of a bugfixing version of
2.4 long ago with just those few patches, let me know what you think.
